# Generated by Django 6.0.1 on 2026-02-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_mgr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='tracking_number',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
